<?php

$htmlForm .= $form->addInput('hidden', 'idProdutoIndicacao', null, array('value'=> '1'), false, false, true);
$htmlForm .= '<div class="panel panel-default">';
$htmlForm .= '<div class="panel-heading">Informações da indicação</div>';
$htmlForm .= '<div class="panel-body">';
$htmlForm .= '<div class="row">';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addSelect('idTipoOperacao', array(), '-1', 'Operação*', array('validate' => 'required', 'class' => 'form-control select2'), false, false, true, '', 'Selecione...', true, true) ;
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addSelect('idTipoUso', array(), '-1', 'Tipo de uso*', array('validate' => 'required', 'class' => 'form-control select2'), false, false, true, '', 'Selecione...', true, true) ;
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addSelect('idTipoImovel', array('0' => '-----'), '', 'Tipo do imóvel*', array('validate' => 'required', 'class' => 'form-control select2', 'disabled' => 'disabled'), false, false, true, '', 'Selecione...', true, true) ;
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addInput('text', 'ValorBem', 'Valor do bem*', array('class' => 'form-control moeda', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= $form->addInput('text', 'PrimeiroBairroPreferencia', 'Bairro de preferência (1)', array('class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= $form->addInput('text', 'SegundoBairroPreferencia', 'Bairro de preferência (2)', array('class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= $form->addInput('text', 'TerceiroBairroPreferencia', 'Bairro de preferência (3)', array('class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-12">';
$htmlForm .= $form->addTextarea('Observacao', '', 'Observação', array('class' => 'form-control'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '</div>';
$htmlForm .= '</div>';
$htmlForm .= '</div>';