<?php
// Cliente
$htmlForm .= '<div class="panel panel-default">';
$htmlForm .= '<div class="panel-heading">Dados do cliente</div>';
$htmlForm .= '<div class="panel-body">';
$htmlForm .= '<div class="row">';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= $form->addInput('text', 'Cliente', 'Nome*', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= $form->addInput('email', 'Email', 'Email*', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= '<div class="control-group">';
$htmlForm .= '<div>Tipo</div>';
$htmlForm .= $form->addRadio('tipo', 'Pessoa física', array('checked' => 'checked', 'value' => 'PF', 'name' => 'TipoCliente'), true);
$htmlForm .= $form->addRadio('tipo', 'Pessoa juridica', array('value' => 'PJ', 'name' => 'TipoCliente'), true);
$htmlForm .= '</div>';
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3" style="clear:both">';
$htmlForm .= $form->addInput('text', 'CPF', 'CPF*', array('validate' => 'required', 'class' => 'form-control cpf_cnpj', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addInput('text', 'Telefone', 'Telefone*', array('validate' => 'required', 'class' => 'form-control telefone', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addInput('text', 'Celular', 'Celular', array('class' => 'form-control telefone', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addInput('date', 'nascimento', 'Nascimento', array('class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-3">';
$htmlForm .= $form->addSelect('Sexo', array('M' => 'Masculino', 'F' => 'Feminino'), '-1', 'Sexo', array('validate' => 'required', 'class' => 'form-control'), false, false, true, '', 'Selecione...', true, true) ;
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-9">';
$htmlForm .= $form->addInput('text', 'Contato', 'Contato', array('class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '</div>';
$htmlForm .= '</div>';
$htmlForm .= '</div>';

// Endereço
$htmlForm .= '<div class="panel panel-default">';
$htmlForm .= '<div class="panel-heading">Endereço</div>';
$htmlForm .= '<div class="panel-body">';
$htmlForm .= '<div class="row">';
$htmlForm .= '<div class="col-md-2">';
$htmlForm .= $form->addInput('text', 'cep', 'CEP*', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-10">';
$htmlForm .= $form->addInput('text', 'endereco', 'Endereço', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-2">';
$htmlForm .= $form->addInput('number', 'numero', 'Número', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= $form->addInput('text', 'bairro', 'Bairro', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off', 'disabled' => 'disabled'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-4">';
$htmlForm .= $form->addInput('text', 'cidade', 'Cidade', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off', 'disabled' => 'disabled'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '<div class="col-md-2">';
$htmlForm .= $form->addInput('text', 'estado', 'Estado', array('validate' => 'required', 'class' => 'form-control', 'autocomplete' => 'off', 'disabled' => 'disabled'), false, false, true);
$htmlForm .= '</div>';
$htmlForm .= '</div>';
$htmlForm .= '</div>';
$htmlForm .= '</div>';
